"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = 'ember_retro'

format = """
[┌─](fg:amber)$os[ $username@$hostname ](fg:cream bg:rust)[ $directory ](fg:dark bg:amber)$git_branch$git_status$cmd_duration
[└─](fg:amber)$character"""
right_format = "$time"

[palettes.ember_retro]
dark = '#211A17'
rust = '#9C3F1F'
amber = '#E89B32'
cream = '#FFE0A3'
green = '#A7C957'
red = '#D1495B'
brown = '#6F4E37'

[os]
disabled = false
style = 'fg:cream bg:rust bold'
format = '[ $symbol ]($style)'

[os.symbols]
AIX = '󰣇'
Alpaquita = ''
AlmaLinux = ''
Alpine = ''
ALTLinux = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = ''
Artix = ''
Bazzite = '󰊴'
Bluefin = '󰈺'
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Elementary = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Kali = ''
KDENeon = ''
Linux = ''
Macos = ''
Manjaro = ''
Mint = ''
NixOS = ''
Nobara = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'
Zorin = ''

[username]
show_always = true
style_user = 'fg:cream bg:rust bold'
style_root = 'fg:cream bg:red bold'
format = '[󰀄 $user]($style)'

[hostname]
ssh_only = false
style = 'fg:cream bg:rust bold'
format = '[$hostname ]($style)'

[directory]
style = 'fg:dark bg:amber bold'
format = '[󰉋 $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = ' 󰌾'

[git_branch]
symbol = '󰘬 '
style = 'fg:cream bg:brown'
format = '[ $symbol$branch ]($style)'

[git_status]
style = 'fg:amber bg:brown'
format = '[$all_status$ahead_behind ]($style)'
untracked = '? '
modified = '! '
staged = '+ '
ahead = '⇡${count} '
behind = '⇣${count} '
deleted = '✘ '

[cmd_duration]
min_time = 1500
style = 'fg:cream'
format = '[ 󰔟 $duration ]($style)'

[time]
disabled = false
time_format = '%H:%M'
style = 'fg:amber'
format = '[CRT $time]($style)'

[character]
success_symbol = '[>](bold fg:amber)'
error_symbol = '[>](bold fg:red)'
vicmd_symbol = '[<](bold fg:green)'

[status]
disabled = false
style = 'fg:red bold'
format = '[ ERR:$status ]($style)'
