"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
palette = 'frostline'

format = """
$os\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$package\
$character"""

right_format = """$cmd_duration$status"""

[palettes.frostline]
navy = '#2E3440'
slate = '#3B4252'
white = '#ECEFF4'
ice = '#88C0D0'
blue = '#5E81AC'
green = '#A3BE8C'
yellow = '#EBCB8B'
red = '#BF616A'
purple = '#B48EAD'

[os]
disabled = false
style = 'fg:ice bold'
format = '[$symbol ]($style)'

[os.symbols]
AIX = '󰣇'
Alpaquita = ''
AlmaLinux = ''
Alpine = ''
ALTLinux = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = ''
Artix = ''
Bazzite = '󰊴'
Bluefin = '󰈺'
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Elementary = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Kali = ''
KDENeon = ''
Linux = ''
Macos = ''
Manjaro = ''
Mint = ''
NixOS = ''
Nobara = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'
Zorin = ''

[directory]
style = 'fg:white bold'
format = '[󰉋 $path]($style)[$read_only]($style) '
truncation_length = 3
truncation_symbol = '…/'
read_only = ' 󰌾'
home_symbol = '~'

[git_branch]
symbol = '󰘬 '
style = 'fg:ice bold'
format = 'on [$symbol$branch ]($style)'

[git_state]
style = 'fg:purple bold'
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
rebase = 'REBASE'
merge = 'MERGE'
cherry_pick = 'CHERRY-PICK'
bisect = 'BISECT'

[git_status]
style = 'fg:yellow'
format = '[$all_status$ahead_behind]($style) '
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
untracked = '?'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'
conflicted = '='
stashed = '≡'

[python]
symbol = '󰌠 '
style = 'fg:blue'
format = 'via [$symbol$version ]($style)'

[nodejs]
symbol = '󰎙 '
style = 'fg:green'
format = 'via [$symbol$version ]($style)'

[rust]
symbol = '󱘗 '
style = 'fg:yellow'
format = 'via [$symbol$version ]($style)'

[golang]
symbol = '󰟓 '
style = 'fg:ice'
format = 'via [$symbol$version ]($style)'

[package]
symbol = '󰏗 '
style = 'fg:slate'
format = '[$symbol$version ]($style)'

[cmd_duration]
min_time = 2000
style = 'fg:slate italic'
format = '[󰔟 $duration]($style) '

[character]
success_symbol = '[❯](bold fg:ice)'
error_symbol = '[❯](bold fg:red)'
vicmd_symbol = '[❮](bold fg:blue)'

[status]
disabled = false
style = 'fg:red bold'
format = '[✘ $status]($style)'

[line_break]
disabled = true