"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = 'monochrome_orbit'

format = """
[╭─](fg:dim)$os$directory$git_branch$git_status$cmd_duration
[╰─](fg:dim)$character"""

[palettes.monochrome_orbit]
black = '#161616'
dim = '#666666'
gray = '#A0A0A0'
white = '#F2F2F2'
accent = '#C4B5FD'
red = '#FF6B6B'

[os]
disabled = false
style = 'fg:gray'
format = '[$symbol ]($style)'

[os.symbols]
Arch = '󰣇'
CachyOS = '󰣇'
EndeavourOS = '󰣇'
Linux = '󰌽'

[directory]
style = 'fg:white bold'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = ' 󰌾'

[git_branch]
symbol = 'git:'
style = 'fg:accent'
format = '[$symbol$branch ]($style)'

[git_status]
style = 'fg:gray'
format = '[$all_status$ahead_behind]($style)'
untracked = '? '
modified = '! '
staged = '+ '
ahead = '↑${count} '
behind = '↓${count} '
deleted = 'x '

[cmd_duration]
min_time = 2000
style = 'fg:dim'
format = '[$duration ]($style)'

[character]
success_symbol = '[●](bold fg:accent)'
error_symbol = '[●](bold fg:red)'
vicmd_symbol = '[○](bold fg:gray)'

[status]
disabled = false
style = 'fg:red'
format = '[exit $status ]($style)'

[line_break]
disabled = false
