"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = 'monochrome_orbit'

format = """
[╭─](fg:dim)$os$directory$git_branch$git_status$cmd_duration
[╰─](fg:dim)$character"""

[palettes.monochrome_orbit]
black = '#111111'
charcoal = '#1A1A1A'
dim = '#6D6D6D'
gray = '#B7B7B7'
soft = '#E8E8E8'
white = '#F5F5F5'
accent = '#C9B8FF'
accent_soft = '#D9D1FF'
red = '#FF7A7A'

[os]
disabled = false
style = 'fg:gray bold'
format = '[$symbol ]($style)'

[os.symbols]
AIX = '󰣇'
Alpaquita = ''
AlmaLinux = ''
Alpine = ''
ALTLinux = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = ''
Artix = ''
Bazzite = '󰊴'
Bluefin = '󰈺'
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Elementary = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Kali = ''
KDENeon = ''
Linux = ''
Macos = ''
Manjaro = ''
Mint = ''
NixOS = ''
Nobara = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'
Zorin = ''

[directory]
style = 'fg:white bold'
format = '[ 󰉋 $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = ' 󰌾'

[git_branch]
symbol = ' '
style = 'fg:accent_soft bold'
format = '[$symbol$branch ]($style)'

[git_status]
style = 'fg:gray'
format = '[$all_status$ahead_behind ]($style)'
untracked = '? '
modified = '! '
staged = '+ '
ahead = '↑${count} '
behind = '↓${count} '
deleted = 'x '

[cmd_duration]
min_time = 2000
style = 'fg:dim'
format = '[󰔟 $duration ]($style)'

[character]
success_symbol = '[●](bold fg:accent)'
error_symbol = '[●](bold fg:red)'
vicmd_symbol = '[○](bold fg:gray)'

[status]
disabled = false
style = 'fg:red bold'
format = '[✘ $status ]($style)'

[line_break]
disabled = false
