"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = 'neon_shogun'

format = """
[╭─](fg:dim)[](fg:crimson)$os$username[](fg:crimson bg:surface)$directory[](bg:surface fg:crimson)$git_branch$git_status[](fg:crimson)
[╰─](fg:dim)$character"""
right_format = "$status$cmd_duration$time"

[palettes.neon_shogun]
black      = '#0C0A0D'
surface    = '#1C1518'
overlay    = '#2A1D22'
foreground = '#E9DCCB'
dim        = '#6E5A60'
crimson    = '#8C2F3B'
blood      = '#5E1F26'
gold       = '#C4964F'
pink       = '#B97896'
cyan       = '#5FA39C'
green      = '#7FA88C'

[os]
disabled = false
style = 'bg:crimson fg:foreground bold'
format = '[ $symbol ]($style)'

[os.symbols]
AIX = '󰣇'
Alpaquita = ''
AlmaLinux = ''
Alpine = ''
ALTLinux = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = ''
Artix = ''
Bazzite = '󰊴'
Bluefin = '󰈺'
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Elementary = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Kali = ''
KDENeon = ''
Linux = ''
Macos = ''
Manjaro = ''
Mint = ''
NixOS = ''
Nobara = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'
Zorin = ''

[username]
show_always = true
style_user = 'bg:crimson fg:foreground bold'
style_root = 'bg:gold fg:black bold'
format = '[( $user )]($style)'

[directory]
style = 'bg:surface fg:gold bold'
format = '[( 󰉋 $path )]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = ' 󰌾'

[git_branch]
symbol = '󰘬 '
style = 'bg:crimson fg:foreground bold'
format = '[( $symbol$branch )]($style)'

[git_status]
style = 'bg:surface fg:pink bold'
format = '[$all_status$ahead_behind ]($style)'
conflicted = '󰞇 '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕ '
untracked = '•${count} '
modified = '!${count} '
staged = '+${count} '
renamed = '»${count} '
deleted = '×${count} '
stashed = '󰏗${count} '

[cmd_duration]
min_time = 1500
style = 'fg:cyan bold'
format = '[ 󰔟 $duration ]($style)'

[time]
disabled = false
time_format = '%H:%M'
style = 'fg:dim'
format = '[  󰥔 $time ]($style)'

[character]
success_symbol = '[刀](bold fg:crimson)'
error_symbol = '[刀](bold fg:blood)'
vicmd_symbol = '[侍](bold fg:cyan)'

[status]
disabled = false
style = 'fg:blood bold'
format = '[✘ $status ]($style)'
