"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
palette = 'oceanic_pulse'

format = """
[](fg:blue)$os$directory[](fg:deep bg:teal)$git_branch$git_status[](fg:teal)
$character"""
right_format = "$python$nodejs$rust$golang$docker_context$kubernetes$cmd_duration$time$status"

[palettes.oceanic_pulse]
deep = '#102A43'
blue = '#268BD2'
teal = '#2EC4B6'
cyan = '#7FDBFF'
foam = '#E0FBFC'
coral = '#FF6B6B'
yellow = '#FFD166'
green = '#6EE7B7'

[os]
disabled = false
style = 'bg:blue fg:foam bold'
format = '[ $symbol ]($style)'

[os.symbols]
AIX = '󰣇'
Alpaquita = ''
AlmaLinux = ''
Alpine = ''
ALTLinux = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = ''
Artix = ''
Bazzite = '󰊴'
Bluefin = '󰈺'
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Elementary = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Kali = ''
KDENeon = ''
Linux = ''
Macos = ''
Manjaro = ''
Mint = ''
NixOS = ''
Nobara = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'
Zorin = ''

[directory]
style = 'bg:deep fg:foam bold'
format = '[ 󰉋 $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = ' 󰌾'

[git_branch]
symbol = '󰘬 '
style = 'bg:teal fg:deep bold'
format = '[ $symbol$branch ]($style)'

[git_status]
style = 'bg:teal fg:deep bold'
format = '[$all_status$ahead_behind ]($style)'
untracked = '? '
modified = '! '
staged = '+ '
ahead = '⇡${count} '
behind = '⇣${count} '
deleted = '✘ '

[character]
success_symbol = '[❯](bold fg:teal)'
error_symbol = '[❯](bold fg:coral)'
vicmd_symbol = '[❮](bold fg:cyan)'

[python]
symbol = '󰌠 '
style = 'fg:cyan'
format = '[$symbol$version ]($style)'
[nodejs]
symbol = '󰎙 '
style = 'fg:green'
format = '[$symbol$version ]($style)'
[rust]
symbol = '󱘗 '
style = 'fg:coral'
format = '[$symbol$version ]($style)'
[golang]
symbol = '󰟓 '
style = 'fg:cyan'
format = '[$symbol$version ]($style)'
[docker_context]
symbol = '󰡨 '
style = 'fg:blue'
format = '[$symbol$context ]($style)'
[kubernetes]
disabled = false
symbol = '󱃾 '
style = 'fg:teal'
format = '[$symbol$context ]($style)'
[cmd_duration]
min_time = 1500
style = 'fg:yellow'
format = '[󰔟 $duration ]($style)'
[time]
disabled = false
time_format = '%H:%M'
style = 'fg:foam'
format = '[󰥔 $time]($style)'
[status]
disabled = false
style = 'fg:coral bold'
format = '[✘$status ]($style)'