"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
palette = 'sakura_dawn'

format = "$os$username$directory$git_branch$git_status$cmd_duration$status$character"

[palettes.sakura_dawn]
ink = '#2F2436'
plum = '#6D5576'
petal = '#F8D9E7'
rose = '#E88EB0'
blossom = '#F6B9CE'
lavender = '#C9B8F2'
mist = '#F8F3F7'
leaf = '#89B7A0'
peach = '#F2C6A0'
red = '#D8677A'
soft_gray = '#8A7F91'

[os]
disabled = false
style = 'bg:petal fg:ink bold'
format = '[ $symbol ]($style)'

[os.symbols]
AIX = '󰣇'
Alpaquita = ''
AlmaLinux = ''
Alpine = ''
ALTLinux = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = ''
Artix = ''
Bazzite = '󰊴'
Bluefin = '󰈺'
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Elementary = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Kali = ''
KDENeon = ''
Linux = ''
Macos = ''
Manjaro = ''
Mint = ''
NixOS = ''
Nobara = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'
Zorin = ''

[username]
show_always = false
style_user = 'bg:lavender fg:ink bold'
style_root = 'bg:red fg:mist bold'
format = '[ $user ]($style)'

[directory]
style = 'bg:rose fg:ink bold'
format = '[ 󰉋 $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = ' 󰌾'

[git_branch]
symbol = ' '
style = 'bg:lavender fg:ink bold'
format = '[ $symbol$branch ]($style)'

[git_status]
style = 'fg:rose bold'
format = '[$all_status$ahead_behind ]($style)'
untracked = '✿? '
modified = '✿! '
staged = '✿+ '
ahead = '⇡${count} '
behind = '⇣${count} '
deleted = '✘ '

[cmd_duration]
min_time = 2000
style = 'fg:soft_gray bold'
format = '[ 󰔟 $duration ]($style)'

[character]
success_symbol = '[❯](bold fg:blossom)'
error_symbol = '[❯](bold fg:red)'
vicmd_symbol = '[❮](bold fg:lavender)'

[status]
disabled = false
style = 'fg:red bold'
format = '[✘$status ]($style)'