"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = 'sakura_dawn'

format = "$os$username$directory$git_branch$git_status$cmd_duration$status$character"

[palettes.sakura_dawn]
ink = '#2E2432'
rose = '#E889B5'
blush = '#F6C8D8'
petal = '#F9EAF3'
lavender = '#B79AE8'
soft_gray = '#7D6E82'
mist = '#FFF8FB'
leaf = '#7FAF97'
peach = '#F2C39B'
red = '#D86A7A'

[os]
disabled = false
style = 'fg:rose bold'
format = '[$symbol ]($style)'

[os.symbols]
AIX = '󰣇'
Alpaquita = ''
AlmaLinux = ''
Alpine = ''
ALTLinux = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = ''
Artix = ''
Bazzite = '󰊴'
Bluefin = '󰈺'
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Elementary = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Kali = ''
KDENeon = ''
Linux = ''
Macos = ''
Manjaro = ''
Mint = ''
NixOS = ''
Nobara = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'
Zorin = ''

[username]
show_always = false
style_user = 'fg:soft_gray bold'
style_root = 'fg:red bold'
format = '[$user ]($style)'

[directory]
style = 'fg:ink bold'
format = '[󰉋 $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = ' 󰌾'

[git_branch]
symbol = ' '
style = 'fg:lavender bold'
format = '[$symbol$branch ]($style)'

[git_status]
style = 'fg:rose'
format = '[$all_status$ahead_behind ]($style)'
untracked = '✦? '
modified = '✦! '
staged = '✦+ '
ahead = '⇡${count} '
behind = '⇣${count} '
deleted = '✘ '

[cmd_duration]
min_time = 2000
style = 'fg:soft_gray'
format = '[󰔟 $duration ]($style)'

[character]
success_symbol = '[❯](bold fg:rose)'
error_symbol = '[❯](bold fg:red)'
vicmd_symbol = '[❮](bold fg:lavender)'

[status]
disabled = false
style = 'fg:red bold'
format = '[✘$status ]($style)'