"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
palette = 'void_circuit'

format = "$os$directory$git_branch$git_status$character"
right_format = "$status$cmd_duration"

[palettes.void_circuit]
void = '#0B0F10'
white = '#D8F3DC'
lime = '#7CFF6B'
cyan = '#38E8DE'
dim = '#52796F'
red = '#FF5D73'
yellow = '#E9FF70'

[os]
disabled = false
style = 'fg:lime bold'
format = '[$symbol ]($style)'

[os.symbols]
AIX = '󰣇'
Alpaquita = ''
AlmaLinux = ''
Alpine = ''
ALTLinux = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = ''
Artix = ''
Bazzite = '󰊴'
Bluefin = '󰈺'
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Elementary = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Kali = ''
KDENeon = ''
Linux = ''
Macos = ''
Manjaro = ''
Mint = ''
NixOS = ''
Nobara = ''
OpenBSD = ''
openSUSE = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'
Zorin = ''

[directory]
style = 'fg:white'
format = '[$path ]($style)'
truncation_length = 2
truncation_symbol = '…/'
read_only = ' lock'

[git_branch]
symbol = ''
style = 'fg:cyan'
format = '[$branch ]($style)'

[git_status]
style = 'fg:yellow'
format = '[$all_status$ahead_behind]($style)'
untracked = '? '
modified = '~ '
staged = '+ '
ahead = '↑${count} '
behind = '↓${count} '
diverged = '↕ '
deleted = '- '

[character]
success_symbol = '[›](bold fg:lime)'
error_symbol = '[›](bold fg:red)'
vicmd_symbol = '[‹](bold fg:cyan)'

[status]
disabled = false
style = 'fg:red'
format = '[$status ]($style)'

[cmd_duration]
min_time = 1000
style = 'fg:dim'
format = '[$duration]($style)'

[line_break]
disabled = true
